# Generated by Django 5.0.6 on 2024-07-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'sections',
                'managed': False,
            },
        ),
    ]
