# Generated by Django 5.0.6 on 2024-07-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id_qualification', models.AutoField(primary_key=True, serialize=False)),
                ('qualification', models.IntegerField()),
                ('feedback', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ratings',
                'managed': False,
            },
        ),
    ]
