# Generated by Django 5.0.6 on 2024-06-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id_bootcamp', models.AutoField(primary_key=True, serialize=False)),
                ('bootcamp', models.CharField(max_length=120)),
            ],
        ),
    ]
