# Generated by Django 5.0.6 on 2024-07-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0002_alter_bootcamp_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id_challenge', models.AutoField(primary_key=True, serialize=False)),
                ('challenge', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'challenges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id_content', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'contents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id_module', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id_qualification', models.AutoField(primary_key=True, serialize=False)),
                ('qualification', models.IntegerField()),
                ('feedback', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'sections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_student', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='bootcamp',
            table='bootcamps',
        ),
    ]
