# Generated by Django 5.0.6 on 2024-07-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0003_challenge_content_module_rating_section_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
