# Generated by Django 5.0.6 on 2024-07-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id_content', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'contents',
                'managed': False,
            },
        ),
    ]
